GET http://localhost:3000/item

###############################################################
GET http://localhost:3000/item/5fd91c2922ba2d1544d86537
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDgwNzQzOTV9.oAeczq2BW1eIgIeCPl6G9A8woFrIP19bDPVLW5gl2YE

###############################################################

POST http://localhost:3000/item
content-type: application/json

{
    "name": "sample 5",
    "description": "sample description 5",
    "price": "10"
}

###############################################################

PUT http://localhost:3000/item/5fda90bb1b7de039544f763c
content-type: application/json

{
    "name": "sample 2 edited",
    "description": "sample description 2",
    "price": "20"
}

###############################################################

DELETE  http://localhost:3000/item/5fd936ab41d85845f4cf3538

###############################################################

POST http://localhost:3000/auth/login
content-type: application/json

{
    "userName": "user"
}